export const EmailNamesData = 
{
    "gautamaakshi@iitgn.ac.in" 	:	"Aakshi gautam" 	,
  "desai.aadesh@iitgn.ac.in" 	:	"Aadesh Desai" 	,
  "aanchalsharma@iitgn.ac.in" 	:	"Aanchal"  	,
  "abhigyan.mn@iitgn.ac.in"  	:	"Abhigyan Martin Ninama"  	,
  "abhilashahazarika@iitgn.ac.in" 	:	"Abhilasha Hazarika"  	,
  "gsv.abhiram@iitgn.ac.in"  	:	"Abhiram Geddam "  	,
  "janagal.a@iitgn.ac.in" 	:	"Abhishek Janagal" 	,
  "abhishek.gy@iitgn.ac.in"  	:	"Abhishek Yawalkar" 	,
  "kanojia.achal@iitgn.ac.in" 	:	"Achal Kanojia" 	,
  "adarsh.g@iitgn.ac.in" 	:	"Adarsh Golait" 	,
  "bhargavaaditi@iitgn.ac.in" 	:	"Aditi bhargava"  	,
  "s.aditya@iitgn.ac.in" 	:	"Aditya Shakya" 	,
  "aditya.ss@iitgn.ac.in" 	:	"Aditya Shekhar"  	,
  "ahhiemegha@iitgn.ac.in"  	:	"Ahhie Megha"  	,
  "karwasara.a@iitgn.ac.in"  	:	"Ajay Karwasara"  	,
  "kumar_akash@iitgn.ac.in"  	:	"Akash Kumar"  	,
  "akhilesh.c@iitgn.ac.in"  	:	"Akhilesh Chauhan" 	,
  "akshay.c@iitgn.ac.in" 	:	"Akshay Chourasiya" 	,
  "alokpradhan@iitgn.ac.in"  	:	"Alok Pradhan " 	,
  "baitamey@iitgn.ac.in" 	:	"Amey Bait" 	,
  "amisharastogi@iitgn.ac.in" 	:	"Amisha Rastogi"  	,
  "amiteshsabut@iitgn.ac.in" 	:	"Amitesh " 	,
  "aniketlakhpati@iitgn.ac.in"  	:	"Aniket G Lakhpati" 	,
  "aniket.r@iitgn.ac.in" 	:	"Aniket Rajnish"  	,
  "walekaraniket@iitgn.ac.in" 	:	"Aniket Walekar"  	,
  "anjali.mg@iitgn.ac.in" 	:	"Anjali Milind Gawai"  	,
  "dhimanankit@iitgn.ac.in"  	:	"Ankit Dhiman " 	,
  "jamaneankita@iitgn.ac.in" 	:	"Ankita Jamane "  	,
  "ankitajains@iitgn.ac.in"  	:	"Ankita Kumari Jain"  	,
  "yadavankita@iitgn.ac.in"  	:	"Ankita Yadav" 	,
  "anushka.n@iitgn.ac.in" 	:	"Anushka Niti" 	,
  "arjunyadav@iitgn.ac.in"  	:	"Arjun Yadav"  	,
  "arushi.a@iitgn.ac.in" 	:	"Arushi Arnav" 	,
  "aryamann.t@iitgn.ac.in"  	:	"Aryamann Tomar"  	,
  "aryan.js@iitgn.ac.in" 	:	"Aryan Shah"  	,
  "ashuashu@iitgn.ac.in" 	:	"Ashu" 	,
  "ashwani.rs@iitgn.ac.in"  	:	"Ashwani Rai"  	,
  "avinash.k@iitgn.ac.in" 	:	"Avinash Kumar" 	,
  "ayush_anand@iitgn.ac.in"  	:	"Ayush Anand"  	,
  "ayushsrivastava@iitgn.ac.in"  	:	"Ayush Srivastava" 	,
  "ayushibhatt@iitgn.ac.in"  	:	"Ayushi Bhatt" 	,
  "meenabhagchand@iitgn.ac.in"  	:	"Bhagchand Meena " 	,
  "bhanumarri@iitgn.ac.in"  	:	"Bhanu Prasad " 	,
  "bhoomika.m@iitgn.ac.in"  	:	"Bhoomika Mandloi" 	,
  "shashikant.gc@iitgn.ac.in" 	:	"Chaitanya Guntoorkar" 	,
  "sharmachanchal@iitgn.ac.in"  	:	"Chanchal Sharma"  	,
  "chetan.k@iitgn.ac.in" 	:	"Chetan Kishore"  	,
  "kesarisinhchauhan@iitgn.ac.in" 	:	"Chetansinh Chauhan"  	,
  "sreevidya.c@iitgn.ac.in"  	:	"Chintalapati Sreevidya"  	,
  "chitranjanjha@iitgn.ac.in" 	:	"Chitranjan Kumar Jha" 	,
  "darsanavarier@iitgn.ac.in" 	:	"Darsana J Varier" 	,
  "deekshagautam@iitgn.ac.in" 	:	"Deeksha Gautam"  	,
  "deep.d@iitgn.ac.in"	:	"Deep Dave" 	,
  "deepak.p@iitgn.ac.in" 	:	"Deepak Patel" 	,
  "singh.deepak@iitgn.ac.in" 	:	"Deepak Singh" 	,
  "denishtrivedi@iitgn.ac.in" 	:	"Denish Trivedi"  	,
  "dhanashree.is@iitgn.ac.in" 	:	"Dhanashree Ingale" 	,
  "kmr.dheeraj@iitgn.ac.in"  	:	"Dheeraj Kumar" 	,
  "dhruv.d@iitgn.ac.in"  	:	"Dhruv Darda"  	,
  "dhvani.ms@iitgn.ac.in" 	:	"Dhvani Shah"  	,
  "divyanshu.m@iitgn.ac.in"  	:	"Divyanshu Meena"  	,
  "eshan.rg@iitgn.ac.in" 	:	"Eshan Gujarathi"  	,
  "eshika.p@iitgn.ac.in" 	:	"Eshika Pathak" 	,
  "shanavas.cf@iitgn.ac.in"  	:	"Faheem Shanavas"  	,
  "fulmonimunda@iitgn.ac.in" 	:	"Fulmoni Munda "  	,
  "gbh.vardhan@iitgn.ac.in"  	:	"G B Harsha Vardhan"  	,
  "sharma.gaurav@iitgn.ac.in" 	:	"Gaurav Sharma" 	,
  "viramgami.g@iitgn.ac.in"  	:	"Gaurav Viramgami" 	,
  "gautam.pv@iitgn.ac.in" 	:	"Gautam Vashishtha" 	,
  "gayatrinerpagar@iitgn.ac.in"  	:	"Gayatri Nerpagar " 	,
  "girivendrayadav@iitgn.ac.in"  	:	"Girivendra Pratap Yadav"  	,
  "gopikavelayudhan@iitgn.ac.in" 	:	"Gopika"  	,
  "manoj.gtr@iitgn.ac.in" 	:	"Gunuru Manoj Taraka Ramarao"  	,
  "dudhatra.p@iitgn.ac.in"  	:	"Harsh Dudhatra"  	,
  "harsh.mv@iitgn.ac.in" 	:	"Harsh Mandalia"  	,
  "harsh.mn@iitgn.ac.in" 	:	"Harshavardhan Naik"  	,
  "harshil.p@iitgn.ac.in" 	:	"Harshil Purohit"  	,
  "himanshu.s@iitgn.ac.in"  	:	"Himanshu Singhal " 	,
  "hiral.s@iitgn.ac.in"  	:	"Hiral Sharma" 	,
  "hitarth.g@iitgn.ac.in" 	:	"Hitarth Gandhi"  	,
  "ferwani.hiten@iitgn.ac.in" 	:	"Hiten Ferwani "  	,
  "kumarhitesh@iitgn.ac.in"  	:	"Hitesh Kumar " 	,
  "hiteshpradhan@iitgn.ac.in" 	:	"Hitesh Pradhan"  	,
  "hrushti.n@iitgn.ac.in" 	:	"hrushti naik" 	,
  "insha.m@iitgn.ac.in"  	:	"Insha Mansuri" 	,
  "bayad.ij@iitgn.ac.in" 	:	"Isha Bayad"  	,
  "sunil.pi@iitgn.ac.in" 	:	"Ishan Prayagi" 	,
  "payyavula.j@iitgn.ac.in"  	:	"Jagadeesh" 	,
  "payyavula.j@iiitgn.ac.in" 	:	"Jagadeesh" 	,
  "jaya.svn@iitgn.ac.in" 	:	"Jayasurya Nalamolu"  	,
  "jetty.h@iitgn.ac.in"  	:	"Jetty Hemasagar " 	,
  "kumar.jitender@iitgn.ac.in"  	:	"Jitender ( Jiten Singh )" 	,
  "parikh.juhi@iitgn.ac.in"  	:	"Juhi Parikh"  	,
  "nandanadilipk@iitgn.ac.in" 	:	"K Nandana Dilip"  	,
  "kamalesh.saha@iitgn.ac.in" 	:	"Kamalesh Saha" 	,
  "kangsabanikkaushik@iitgn.ac.in"  	:	"Kaushik Kangsabanik"  	,
  "keshav.kv@iitgn.ac.in" 	:	"Keshav Kumar Verma"  	,
  "khantilpatel@iitgn.ac.in" 	:	"Khantil Patel" 	,
  "koushik.cc@iitgn.ac.in"  	:	"Koushik Chandra Chenna "  	,
  "krishna.kumar@iitgn.ac.in" 	:	"Krishna Kumar" 	,
  "krishna.mp@iitgn.ac.in"  	:	"Krishna Mohan" 	,
  "krishnam.h@iitgn.ac.in"  	:	"Krishnam Hasija"  	,
  "kritika.k@iitgn.ac.in" 	:	"Kritika Kumawat"  	,
  "likhita.b@iitgn.ac.in" 	:	"Likhita Baswani"  	,
  "madhusmitaray@iitgn.ac.in" 	:	"Madhusmita Ray"  	,
  "malavikakrishna@iitgn.ac.in"  	:	"Malavika" 	,
  "mulpuri.m@iitgn.ac.in" 	:	"Manas Mulpuri" 	,
  "manvendra.s@iitgn.ac.in"  	:	"Manvendra Singh Songara " 	,
  "md.shohail@iitgn.ac.in"  	:	"Md Amir Shohail"  	,
  "bavaria.m@iitgn.ac.in" 	:	"Meet Bavaria" 	,
  "thumar.m@iitgn.ac.in" 	:	"Meet Thumar"  	,
  "ravi.mekala@iitgn.ac.in"  	:	"Mekala Rishitha Ravi " 	,
  "mihir.hc@iitgn.ac.in" 	:	"Mihir Chauhan "  	,
  "mihir.hc@iitgn.ac.in" 	:	"Mihir Chauhan "  	,
  "mohammadasim@iitgn.ac.in" 	:	"Mohammad Asim" 	,
  "mohd.umair@iitgn.ac.in"  	:	"Mohd Umair Iqbal" 	,
  "monika.s@iitgn.ac.in" 	:	"Monika Saini" 	,
  "mrunalchavan@iitgn.ac.in" 	:	"Mrunal"  	,
  "murshidhusain@iitgn.ac.in" 	:	"Murshid Husain"  	,
  "pradhannachiket@iitgn.ac.in"  	:	"Nachiket Pradhan" 	,
  "goyalnamrata@iitgn.ac.in" 	:	"Namrata Goyal "  	,
  "kumarnaveen@iitgn.ac.in"  	:	"Naveen Kumar" 	,
  "neeraj.g@iitgn.ac.in" 	:	"Neeraj Gothwal"  	,
  "nikharv.19110125@iitgn.ac.in" 	:	"Nikharv Shah" 	,
  "nikhilnikhil@iitgn.ac.in" 	:	"Nikhil"  	,
  "nikita.19110190@iitgn.ac.in"  	:	"Nikita"  	,
  "nilabhraadhikary@iitgn.ac.in" 	:	"NILABHRA ADHIKARY" 	,
  "nilabhraadhikary@iitgn.ac.in" 	:	"NILABHRA ADHIKARY" 	,
  "nilachalchakrabarti@iitgn.ac.in"  	:	"Nilachal Chakrabarti" 	,
  "agarwal.nimit@iitgn.ac.in" 	:	"Nimit Agarwal" 	,
  "ninad.ps@iitgn.ac.in" 	:	"Ninad Shah"  	,
  "mahajan.n@iitgn.ac.in" 	:	"Nipun Mahajan" 	,
  "singlanisha@iitgn.ac.in"  	:	"Nisha Singla" 	,
  "chauhannishank@iitgn.ac.in"  	:	"Nishank Chauhan"  	,
  "om.prakash@iitgn.ac.in"  	:	"Om Prakash"  	,
  "paarth.madan@iitgn.ac.in" 	:	"Paarth Madan" 	,
  "paarth.s@iitgn.ac.in" 	:	"Paarth Sachan" 	,
  "pahuni.j@iitgn.ac.in" 	:	"Pahuni Jain"  	,
  "wadhwapalak@iitgn.ac.in"  	:	"Palak Wadhwa" 	,
  "pallav.j@iitgn.ac.in" 	:	"Pallav Jain"  	,
  "gupta.paras@iitgn.ac.in"  	:	"Paras Gupta"  	,
  "jain.paras@iitgn.ac.in"  	:	"Paras Jain"  	,
  "agam.j@iitgn.ac.in"  	:	"Patel Agam"  	,
  "rajan.gp@iitgn.ac.in" 	:	"Patel Rajan Girishbhai "  	,
  "vashisth.p@iitgn.ac.in"  	:	"Patel Vashisth "  	,
  "pradnyapise@iitgn.ac.in"  	:	"Pradnya Pise" 	,
  "praisydavid@iitgn.ac.in"  	:	"Praisy David" 	,
  "kanwat.pranav@iitgn.ac.in" 	:	"Pranav Kanwat" 	,
  "prateek.kj@iitgn.ac.in"  	:	"Prateek Kumar Jha" 	,
  "pratham.kp@iitgn.ac.in"  	:	"Pratham Panchal"  	,
  "preet.ss@iitgn.ac" 	:	"Preet Shah"  	,
  "chandakprerna@iitgn.ac.in" 	:	"Prerna Chandak"  	,
  "pritha.c@iitgn.ac.in" 	:	"Pritha Chakravarti"  	,
  "gurrala.p@iitgn.ac.in" 	:	"Priyanka Gurrala" 	,
  "priyashverma@iitgn.ac.in" 	:	"Priyash Verma" 	,
  "jain.pulkit@iitgn.ac.in"  	:	"Pulkit Jain"  	,
  "kumarpulkit@iitgn.ac.in"  	:	"Pulkit Kumar " 	,
  "lakshmi.nr@iitgn.ac.in"  	:	"R Lakshmi Nageswari"  	,
  "raavi.vp@iitgn.ac.in" 	:	"Raavi Patel"  	,
  "rahibhalekar@iitgn.ac.in" 	:	"Rahi" 	,
  "g.rahul@iitgn.ac.in"  	:	"Rahul Dev" 	,
  "mina.rahul@iitgn.ac.in"  	:	"Rahul Mina "  	,
  "rajatbasak@iitgn.ac.in"  	:	"Rajat Kumar Basak" 	,
  "kashyaprajesh@iitgn.ac.in" 	:	"Rajesh Kashyap"  	,
  "srisaikottu@iitgn.ac.in"  	:	"Rakesh"  	,
  "ramyawarrier@iitgn.ac.in" 	:	"Ramya Warrier "  	,
  "rashikumar@iitgn.ac.in"  	:	"Rashi Kumar"  	,
  "lrenuka@iitgn.ac.in"  	:	"RENUKA L" 	,
  "reuben.sd@iitgn.ac.in" 	:	"Reuben Devanesan" 	,
  "riddhijohri@iitgn.ac.in"  	:	"Riddhi Johri" 	,
  "rishabhpers.24@gmail.com" 	:	"Rishabh Gupta" 	,
  "rishabh.r@iitgn.ac.in" 	:	"Rishabh Rohil" 	,
  "rishitha.b@iitgn.ac.in"  	:	"Rishitha Bikkumalla"  	,
  "ritesh.kmr@iitgn.ac.in"  	:	"Ritesh Kumar" 	,
  "rithik.maligi@iitgn.ac.in" 	:	"Rithik Maligi" 	,
  "vajaritu@iitgn.ac.in" 	:	"Ritu Vaja" 	,
  "dhariarohit@iitgn.ac.in"  	:	"Rohit Dharia" 	,
  "rohit.ss@iitgn.ac.in" 	:	"Rohit Sevalkar"  	,
  "rohith.tkr@iitgn.ac.in"  	:	"Rohith Kumar Reddy"  	,
  "rudresh.r@iitgn.ac.in" 	:	"Rudresh Rai"  	,
  "rupantarchoudhury@iitgn.ac.in" 	:	"Rupantar Choudhury"  	,
  "jatin.rushik@iitgn.ac.in" 	:	"Rushik Desai" 	,
  "sai.mrr@iitgn.ac.in"  	:	"Ruthvik Mula" 	,
  "saagar.p@iitgn.ac.in" 	:	"Saagar Parikh" 	,
  "sumansaatwik@iitgn.ac.in" 	:	"Saatwik Suman" 	,
  "kumarsachin@iitgn.ac.in"  	:	"Sachin Kumar " 	,
  "yadav.sachin@iitgn.ac.in" 	:	"Sachin Yadav" 	,
  "safafathim@iitgn.ac.in"  	:	"Safa Fathim"  	,
  "shubham.sai@iitgn.ac.in"  	:	"Sai Shubham " 	,
  "sai.y@iitgn.ac.in" 	:	"Sai Yashverdhan"  	,
  "earandi.s@iitgn.ac.in" 	:	"Saineeth" 	,
  "jagtap.sakshi@iitgn.ac.in" 	:	"Sakshi Jagtap" 	,
  "sakshisawai@iitgn.ac.in"  	:	"Sakshi Sawai" 	,
  "sambitsahoo@iitgn.ac.in"  	:	"SAMBIT SAHOO" 	,
  "sameer.m@iitgn.ac.in" 	:	"Sameer Khan Mehar" 	,
  "sanchit.m@iitgn.ac.in" 	:	"Sanchit Mittal"  	,
  "venkitesh.s@iitgn.ac.in"  	:	"Sanjay Venkitesh" 	,
  "anil.ns@iitgn.ac.in"  	:	"Sanskar Anil Nalkande "  	,
  "saransh.rc@iitgn.ac.in"  	:	"Saransh Chaudhary" 	,
  "biswas.sayan@iitgn.ac.in" 	:	"Sayan Biswas" 	,
  "shashwatsrivastava@iitgn.ac.in"  	:	"Shashwat " 	,
  "shashwat.rj@iitgn.ac.in"  	:	"Shashwat Jain" 	,
  "shashwat.p@iitgn.ac.in"  	:	"Shashwat Parashar "  	,
  "shauravbhattacharyya@iitgn.ac.in" 	:	"Shaurav Bhattacharyya" 	,
  "shivamchaudhary@iitgn.ac.in"  	:	"Shivam Chaudhary " 	,
  "shivam.r@iitgn.ac.in" 	:	"Shivam Rai"  	,
  "shivani.sharma@alumni.iitgn.ac.in" 	:	"Shivani Sharma "  	,
  "vp.shivasan@iitgn.ac.in"  	:	"Shivasankaran" 	,
  "shreyakapoor@iitgn.ac.in" 	:	"Shreya Kapoor" 	,
  "sai.ssm@iitgn.ac.in"  	:	"Shreya Sama"  	,
  "shreyaschaudhari@iitgn.ac.in" 	:	"Shreyas Chaudhari" 	,
  "shreyash.a@iitgn.ac.in"  	:	"Shreyash Agrawal" 	,
  "shreyshi.s@iitgn.ac.in"  	:	"Shreyshi Singh"  	,
  "sominath.ps@iitgn.ac.in"  	:	"Shridhar Pawar"  	,
  "singh.shrreya@iitgn.ac.in" 	:	"Shrreya Singh" 	,
  "sunil.sl@iitgn.ac.in" 	:	"Shubh Lavti"  	,
  "shubham.kg@iitgn.ac.in"  	:	"Shubham Kewat" 	,
  "shubham.kg@iitgn.ac.in"  	:	"Shubham Kewat" 	,
  "kumar_shubham@iitgn.ac.in" 	:	"Shubham kumar" 	,
  "v.shubham@iitgn.ac.in" 	:	"Shubham Verma" 	,
  "siddharth.j@iitgn.ac.in"  	:	"Siddharth Joshi"  	,
  "siddhi.pravin@iitgn.ac.in" 	:	"Siddhi Surawar "  	,
  "smritisaini@iitgn.ac.in"  	:	"Smriti Saini" 	,
  "sneha.ss@iitgn.ac.in" 	:	"Sneha Sawale" 	,
  "sneha.ss@iitgn.ac.in" 	:	"Sneha Sawale" 	,
  "sneha.ss@iitgn.ac.in" 	:	"Sneha Sawale" 	,
  "snehal.gohad@iitgn.ac.in" 	:	"Snehal Gohad" 	,
  "raj.snehal@iitgn.ac.in"  	:	"Snehal R. Shelke" 	,
  "acharyasoham@iitgn.ac.in" 	:	"Soham "  	,
  "soham.r@iitgn.ac.in"  	:	"Soham Shirodkar"  	,
  "somesh.ps@iitgn.ac.in" 	:	"Somesh Pratap Singh"  	,
  "choudhary_s@iitgn.ac.in"  	:	"Sonal Choudhary"  	,
  "yadav.sourav@iitgn.ac.in" 	:	"Sourav Yadav" 	,
  "sresth.t@iitgn.ac.in" 	:	"Sresth Tosniwal"  	,
  "sreyoshidas@iitgn.ac.in"  	:	"Sreyoshi Das" 	,
  "srinivasamgoth@iitgn.ac.in"  	:	"Srinivas Amgoth"  	,
  "porelsudipta@iitgn.ac.in" 	:	"Sudipta " 	,
  "surabhim@iitgn.ac.in" 	:	"Surabhi Menon" 	,
  "tamma.s@iitgn.ac.in"  	:	"Tamma Sowmya Sri" 	,
  "tamma.s@iitgn.ac.in"  	:	"Tamma Sowmya Sri" 	,
  "tejendra.p@iitgn.ac.in"  	:	"Tejendra Patel"  	,
  "guptatushar@iitgn.ac.in"  	:	"Tushar Gupta" 	,
  "agarwal.umang@iitgn.ac.in" 	:	"Umang Agrawal "  	,
  "upashana.p@iitgn.ac.in"  	:	"Upashana Pankaj"  	,
  "barala.v@iitgn.ac.in" 	:	"Varun Barala" 	,
  "videh.p@iitgn.ac.in"  	:	"Videh Patel"  	,
  "vishal.k@iitgn.ac.in" 	:	"Vishal Kumar" 	,
  "jayesh.s@iitgn.ac.in" 	:	"Vishal Soni"  	,
  "banoth.naik@iitgn.ac.in"  	:	"Vishnu Sai"  	,
  "gohil.vb@iitgn.ac.in" 	:	"Vishwaraj" 	,
  "vridhirohira@iitgn.ac.in" 	:	"Vridhi Rohira" 	,
  "xhitij.cm@iitgn.ac.in" 	:	"Xhitij Choudhary" 	,
  "yash.mh@iitgn.ac.in"  	:	"Yash More" 	,
  "yaswanthmittapalli@iitgn.ac.in"  	:	"Yaswanth Ram" 	,
  "jaybhayeyogesh@iitgn.ac.in"  	:	"Yogesh Jaybhaye"  	,
  "khanzainul@iitgn.ac.in"	:	"Zainul Khan"	

}